version: '3.7'

services:
  # api
  summer-lod-api:
    image: vedph2020/summer-lod-api:0.0.2
    container_name: summer-lod-api
    ports:
      - 5275:8080
    networks:
      - summer-lod-network
    #environment:
    # add allowed origins here, e.g. ALLOWEDORIGINS__0=http://localhost:4200

  # app
  summer-lod-app:
    image: vedph2020/summer-lod-app:0.0.1
    container_name: summer-lod-app
    ports:
      - 4200:80
    depends_on:
      - summer-lod-api
    networks:
      - summer-lod-network

networks:
  summer-lod-network:
    driver: bridge
